apiVersion: v1
kind: Pod
metadata:
  name: mongodb-pod
spec:
  volumes:
    - name: mongodb-pv-storage
      persistentVolumeClaim:
        claimName: mongodb-pv-claim
  containers:
    - name: mongodb-container
      image: mongo:4.4
      ports:
        - containerPort: 27017
          name: "mongo"
      volumeMounts:
        - mountPath: "/data/db"
          name: mongodb-pv-storage
